### ISSUE TITLE
Bad syntax on the about page

### ISSUE THREAD

**Issue by gastbob40** [EpiLink/EpiLink#130]
When we go to the about page, the dot goes before the instance

## Current Result

```
Pour toute question, merci de vous adresser en priorité aux mainteneurs de l'instance. 'EpiLink for EPITA' 
```

## Expected Result

```
Pour toute question, merci de vous adresser en priorité aux mainteneurs de l'instance 'EpiLink for EPITA' .
```

![image](https://user-images.githubusercontent.com/30774494/80288251-18f6cd00-8737-11ea-9954-c0b8838d2582.png)

**Comment by utybo** [comment]
This is a front-end bug, not a back-end bug :)
