### ISSUE TITLE
Add a limit of time for each update of identity setting for the users

### ISSUE THREAD

**Issue by bat021** [EpiLink/EpiLink#169]
Currently, each user can choose to give or hide his identity at all time without any restriction of time.
Should have a configurable time limit (e.g. 5 days) during which the identity setting could not be changed.

**Comment by utybo** [comment]
Not entirely sure of when I'll fix this, so I'm putting this in the 1.0 milestone for now, there's a lot of things I need to do for 0.3 already.

**Comment by utybo** [comment]
Postponing to 1.0
