### ISSUE TITLE
Add command to the discord bot to count members 

### ISSUE THREAD

**Issue by bat021** [EpiLink/EpiLink#242]
A simple `e!count |role` ou `e!count role_id` to count all the members with this role.
Definitely not the best feature, but still useful.

**Comment by utybo** [comment]
Kind of out of scope... this would be better suited for a general purpose bot. Definitely not hard to implement though, I just feel like this is bloat for EpiLink.

**Comment by bat021** [comment]
well it can be useful if you want to see how many people an `e!update` will actually update, it's not much but it's honest work

**Comment by utybo** [comment]
Will be added, probably as a e!count or something, planned for 0.7
