### ISSUE TITLE
Remove the need to define each role and its associated rule

### ISSUE THREAD

**Issue by utybo** [EpiLink/EpiLink#244]
The rule system is currently kind of clumsy to use:

- Each rule is tied to specific roles (requires config to map all the roles in the YAML)
- Each server maps the specific roles to the person, but only if that role was tied to a rule (requires even more config to map each role to a server)

This would remove the need for the roles config here: https://epilink.zoroark.guru/#/MaintainerGuide?id=discord-custom-roles-configuration

Instead of this, we could just call the rules directly in each server, e.g. 

```yaml
# Server def
requires: [ "MyRule", "OtherRule" ]
roles:
  # ...
```

```kotlin
"MyRule" {
    ...
}

"OtherRule" {
    ...
}
```

This can be more error-prone, but is also *much* more flexible.

pinging @Litarvan to know if this is a good idea or not

**Comment by Litarvan** [comment]
Oui monsieur très autorisé
________________________________
