### ISSUE TITLE
Update Discord logo and color

### ISSUE THREAD

**Issue by utybo** [EpiLink/EpiLink#278]
Discord [updated their logo](https://blog.discord.com/happy-blurpthday-to-discord-a-place-for-everything-you-can-imagine-fc99ee0a77c0). Though I'm not a fan of the new one, we have to update the assets used on EpiLink.

I believe there's only stuff to change on the front-end, things to change are:

* The color (I believe we can also just keep the color unmodified, unlike the previous color which was too bright to be readable)
* The logo

@Litarvan t'is a job for you mister front-end

**Comment by Litarvan** [comment]
new logo is cringe, I bet that it will change soon (though probably not a rollback but still)

**Comment by utybo** [comment]
I don't think the logo will change, though the font might. We can still update it right now and, if they do end up changing it, update it *again*. Sticking to guidelines is more important than petty resistance to change.
