### ISSUE TITLE
Investigate back-end being reportedly slow on /register endpoints?

### ISSUE THREAD

**Issue by utybo** [EpiLink/EpiLink#61]
@Litarvan reported some inconsistent slowness on `/register` endpoints. This needs to be investigated.

Potential clues:

* This might be a temporary slowdown due to lazy objects being initialized for the first time (although that's highly unlikely because MS and Discord backends are initialized with the first call to `/meta/info` for retrieving the authorization stub)
* This might be a temporary slowdown due to Microsoft or Discord APIs just being slow
* Redis hiccups?
* Ktor client library initialization? The client side of things might not have been used before the first call, and loading it might take a long time.

Needs to be checked:

* Does this happen on only the first call?

**Comment by Litarvan** [comment]
Considering the fact it never happened again, closing this.
